export const menuData = [
  { id: 1, names: { en: "Baratta", si: "පරාටා", ta: "பரோட்டா" }, category: "breakfast", price: 50 },
  { id: 2, names: { en: "Idiyappam", si: "ඉඳිආප්ප", ta: "இடியப்பம்" }, category: "breakfast", price: 90 },
  { id: 3, names: { en: "Pittu", si: "පිට්ටු", ta: "பிட்டு" }, category: "breakfast", price: 120 },
  { id: 4, names: { en: "Pittu (Mani)", si: "මනි පිට්ටු", ta: "மணி பிட்டு" }, category: "breakfast", price: 100 },
  { id: 5, names: { en: "Paruppu vadai", si: "පරිප්පු වඩේ", ta: "பருப்பு வடை" }, category: "breakfast", price: 30 },
  { id: 6, names: { en: "Thattu Rotti", si: "තට්ටු රොටි", ta: "தட்டு ரொட்டி" }, category: "breakfast", price: 50 },
  { id: 7, names: { en: "Ulundu vadai", si: "උළුඳු වඩේ", ta: "உளுந்து வடை" }, category: "breakfast", price: 80 },
  { id: 8, names: { en: "Koli Appam", si: "කොලි ආප්ප", ta: "கோழி அப்பம்" }, category: "breakfast", price: 60 },
  { id: 9, names: { en: "Iraehchi Rotti", si: "මස් රොටි", ta: "இறைச்சி ரொட்டி" }, category: "breakfast", price: 130 },
  { id: 10, names: { en: "Chicken Rotti", si: "චිකන් රොටි", ta: "கோழி ரொட்டி" }, category: "breakfast", price: 130 },
  { id: 11, names: { en: "Veg Rotti", si: "එළවළු රොටි", ta: "மரக்கறி ரொட்டி" }, category: "breakfast", price: 100 },
  { id: 12, names: { en: "Beef Bun", si: "බීෆ් බන්", ta: "மாட்டிறைச்சி பன்" }, category: "breakfast", price: 150 },
  { id: 13, names: { en: "Chicken Bun", si: "චිකන් බන්", ta: "கோழி பன்" }, category: "breakfast", price: 100 },
  { id: 14, names: { en: "Egg Roll", si: "බිත්තර රෝල්", ta: "முட்டை ரோல்" }, category: "breakfast", price: 130 },
  { id: 15, names: { en: "Samosa Beef/Chicken", si: "සමෝසා බීෆ්/චිකන්", ta: "சமோசா மாட்டிறைச்சி/கோழி" }, category: "breakfast", price: 80 },
  { id: 16, names: { en: "Veg Roll", si: "එළවළු රෝල්", ta: "மரக்கறி ரோல்" }, category: "breakfast", price: 60 },
  { id: 17, names: { en: "Pettes", si: "පැටිස්", ta: "பாட்டிஸ்" }, category: "breakfast", price: 70 },
  { id: 18, names: { en: "Egg Rotti", si: "බිත්තර රොටි", ta: "முட்டை ரொட்டி" }, category: "breakfast", price: 130 },
  { id: 19, names: { en: "Dosa", si: "තෝසේ", ta: "தோசை" }, category: "breakfast", price: 80 },
  { id: 20, names: { en: "Red Rice", si: "රතු බත්", ta: "சிவப்பு அரிசி" }, category: "breakfast", price: 300 },
  { id: 21, names: { en: "Noodles", si: "නූඩ්ලස්", ta: "நூடுல்ஸ்" }, category: "breakfast", price: 330 },
  { id: 22, names: { en: "Chee Rotti", si: "චී රොටි", ta: "சீ ரொட்டி" }, category: "breakfast", price: 180 },
  { id: 23, names: { en: "Cheese Rotti", si: "චීස් රොටි", ta: "சீஸ் ரொட்டி" }, category: "breakfast", price: 150 },
  { id: 24, names: { en: "Lunch Rotti (Veechi Rotti)", si: "වීසි රොටි", ta: "வீச்சு ரொட்டி" }, category: "breakfast", price: 50 },
  { id: 25, names: { en: "Omlet Bun", si: "ඔම්ලට් බන්", ta: "ஆம்லெட் பன்" }, category: "breakfast", price: 120 },
  { id: 26, names: { en: "Rice & Curry (Fish)", si: "බත් සහ මාළු කරි", ta: "சோறு மற்றும் மீன் கறி" }, category: "lunch", price: 500 },
  { id: 27, names: { en: "Rice & Curry (Beef)", si: "බත් සහ බීෆ් කරි", ta: "சோறு மற்றும் மாட்டிறைச்சி கறி" }, category: "lunch", price: 600 },
  { id: 28, names: { en: "Rice & Curry (Chicken)", si: "බත් සහ චිකන් කරි", ta: "சோறு மற்றும் கோழி கறி" }, category: "lunch", price: 550 },
  { id: 29, names: { en: "Rice & Curry (Egg)", si: "බත් සහ බිත්තර කරි", ta: "சோறு மற்றும் முட்டை கறி" }, category: "lunch", price: 400 },
  { id: 30, names: { en: "Rice & Curry (Vegetable)", si: "බත් සහ එළවළු කරි", ta: "சோறு மற்றும் மரக்கறி கறி" }, category: "lunch", price: 300 },
  { id: 31, names: { en: "Beef Malay Nasi Goreng", si: "බීෆ් මැලේ නාසි ගුරාන්", ta: "மாட்டிறைச்சி மலாய் நாசி கோரெங்" }, category: "nasi_goreng", prices: { "Small": 1000, "Medium": 1500, "Large": 3000 } },
  { id: 32, names: { en: "Chicken Malay Nasi Goreng", si: "චිකන් මැලේ නාසි ගුරාන්", ta: "கோழி மலாய் நாசி கோரெங்" }, category: "nasi_goreng", prices: { "Small": 1000, "Medium": 1400, "Large": 2800 } },
  { id: 33, names: { en: "Mixed Malay Nasi Goreng", si: "මික්ස්ඩ් මැලේ නාසි ගුරාන්", ta: "கலப்பு மலாய் நாசி கோரெங்" }, category: "nasi_goreng", prices: { "Small": 1250, "Medium": 1700, "Large": 3500 } },
  { id: 34, names: { en: "Sea Food Malay Nasi Goreng", si: "සී ෆුඩ් මැලේ නාසි ගුරාන්", ta: "கடல் உணவு மலாய் நாசி கோரெங்" }, category: "nasi_goreng", prices: { "Small": 1250, "Medium": 1700, "Large": 3500 } },
  { id: 35, names: { en: "Special Grill Chicken Fried Rice", si: "ස්පෙෂල් ග්‍රිල් චිකන් ෆ්‍රයිඩ් රයිස්", ta: "சிறப்பு கிரில் சிக்கன் ப்ரைட் ரைஸ்" }, category: "grill_chicken", prices: { "Small": 1000, "Medium": 1500, "Large": 3500 } },
  { id: 36, names: { en: "Egg Biriyani", si: "බිත්තර බිරියානි", ta: "முட்டை பிரியாணி" }, category: "biryani", prices: { "Small": 400, "Medium": 650, "Large": 1500 } },
  { id: 37, names: { en: "Vegetable Briyani", si: "එළවළු බිරියානි", ta: "மரக்கறி பிரியாணி" }, category: "biryani", prices: { "Small": 350, "Medium": 550 } },
  { id: 38, names: { en: "Fish Briyani", si: "මාළු බිරියානි", ta: "மீன் பிரியாணி" }, category: "biryani", prices: { "Small": 650, "Medium": 850 } },
  { id: 39, names: { en: "Beef Briyan", si: "බීෆ් බිරියානි", ta: "மாட்டிறைச்சி பிரியாணி" }, category: "biryani", prices: { "Small": 750, "Medium": 950, "Large": 2000 } },
  { id: 40, names: { en: "Chicken Briyani", si: "චිකන් බිරියානි", ta: "கோழி பிரியாணி" }, category: "biryani", prices: { "Small": 700, "Medium": 900, "Large": 2000 } },
  { id: 41, names: { en: "Chicken Koththu", si: "චිකන් කොත්තු", ta: "கோழி கொத்து" }, category: "koththu", prices: { "Small": 700, "Medium": 900 } },
  { id: 42, names: { en: "Prawns Koththu", si: "ඉස්සෝ කොත්තු", ta: "இறால் கொத்து" }, category: "koththu", prices: { "Small": 700, "Medium": 900 } },
  { id: 43, names: { en: "Beef Koththu", si: "බීෆ් කොත්තු", ta: "மாட்டிறைச்சி கொத்து" }, category: "koththu", prices: { "Small": 750, "Medium": 950 } },
  { id: 44, names: { en: "Sea Food Koththu", si: "සී ෆුඩ් කොත්තු", ta: "கடல் உணவு கொத்து" }, category: "koththu", prices: { "Small": 900, "Medium": 1400 } },
  { id: 45, names: { en: "Mixed Koththu", si: "මික්ස්ඩ් කොත්තු", ta: "கலப்பு கொத்து" }, category: "koththu", prices: { "Small": 1100, "Medium": 1500 } },
  { id: 46, names: { en: "Devilled Beef", si: "ඩෙවිල්ඩ් බීෆ්", ta: "டெவில்ட் மாட்டிறைச்சி" }, category: "koththu", prices: { "Small": 900, "Medium": 1300 } },
  { id: 47, names: { en: "Chicken Cheese Koththu", si: "චිකන් චීස් කොත්තු", ta: "கோழி சீஸ் கொத்து" }, category: "koththu", prices: { "Small": 1000, "Medium": 1400 } },
  { id: 48, names: { en: "Beef Cheese Koththu", si: "බීෆ් චීස් කොත්තු", ta: "மாட்டிறைச்சி சீஸ் கொத்து" }, category: "koththu", prices: { "Small": 1100, "Medium": 1500 } },
  { id: 49, names: { en: "Mixed Cheese Koththu", si: "මික්ස්ඩ් චීස් කොත්තු", ta: "கலப்பு சீஸ் கொத்து" }, category: "koththu", prices: { "Small": 1300, "Medium": 1600 } },
  { id: 50, names: { en: "Milk Tea", si: "කිරි තේ", ta: "பால் தேநீர்" }, category: "hot_drinks", price: 160 },
  { id: 51, names: { en: "Milk Powder Tea", si: "කිරිපිටි තේ", ta: "பால் பவுடர் தேநீர்" }, category: "hot_drinks", price: 120 },
  { id: 52, names: { en: "Plain Tea", si: "ප්ලේන් ටී", ta: "வெறும் தேநீர்" }, category: "hot_drinks", price: 50 },
  { id: 53, names: { en: "Plain Tea Special", si: "ස්පෙෂල් ප්ලේන් ටී", ta: "சிறப்பு வெறும் தேநீர்" }, category: "hot_drinks", price: 80 },
  { id: 54, names: { en: "Coffee", si: "කෝපි", ta: "காபி" }, category: "hot_drinks", price: 80 },
  { id: 55, names: { en: "Nest Coffee", si: "නෙස් කෝපි", ta: "நெஸ் காபி" }, category: "hot_drinks", price: 140 },
  { id: 56, names: { en: "Nestomalt", si: "නෙස්ටෝමෝල්ට්", ta: "நெஸ்டோமால்ட்" }, category: "hot_drinks", price: 120 },
  { id: 57, names: { en: "Milk Coffee", si: "කිරි කෝපි", ta: "பால் காபி" }, category: "hot_drinks", price: 150 },
  { id: 58, names: { en: "Kava Tea", si: "කාවා තේ", ta: "காவா தேநீர்" }, category: "hot_drinks", price: 160 },
  { id: 59, names: { en: "Take Away Cup Charges", si: "ටේක් අවේ කෝප්ප ගාස්තු", ta: "பார்சல் கப் கட்டணம்" }, category: "hot_drinks", price: 20 },
  { id: 60, names: { en: "Chicken Palandi Kottu", si: "චිකන් පලන්ඩි කොත්තු", ta: "கோழி பலண்டி கொத்து" }, category: "palandi_kottu", prices: { "Small": "", "Medium": "", "Large": "" } },
  { id: 61, names: { en: "Beef Palandi Kottu", si: "බීෆ් පලන්ඩි කොත්තු", ta: "மாட்டிறைச்சி பலண்டி கொத்து" }, category: "palandi_kottu", prices: { "Small": "", "Medium": "", "Large": "" } },
  { id: 62, names: { en: "Egg Palandi Kottu", si: "බිත්තර පලන්ඩි කොත්තු", ta: "முட்டை பலண்டி கொத்து" }, category: "palandi_kottu", prices: { "Small": "", "Medium": "", "Large": "" } },
  { id: 63, names: { en: "Chicken Bamboo Briyani", si: "චිකන් බම්බු බිරියානි", ta: "கோழி மூங்கில் பிரியாணி" }, category: "bamboo_briyani", prices: { "Small": "", "Medium": "", "Large": "" } },
  { id: 64, names: { en: "Beef Bamboo Briyani", si: "බීෆ් බම්බු බිරියානි", ta: "மாட்டிறைச்சி மூங்கில் பிரியாணி" }, category: "bamboo_briyani", prices: { "Small": "", "Medium": "", "Large": "" } },
  { id: 65, names: { en: "Chicken Palandi Cheese Kottu", si: "චිකන් පලන්ඩි චීස් කොත්තු", ta: "கோழி பலண்டி சீஸ் கொத்து" }, category: "palandi_cheese_kotthu", prices: { "Small": "", "Medium": "", "Large": "" } },
  { id: 66, names: { en: "Beef Palandi Cheese Kottu", si: "බීෆ් පලන්ඩි චීස් කොත්තු", ta: "மாட்டிறைச்சி பலண்டி சீஸ் கொத்து" }, category: "palandi_cheese_kotthu", prices: { "Small": "", "Medium": "", "Large": "" } },
  { id: 67, names: { en: "Egg Palandi Cheese Kottu", si: "බිත්තර පලන්ඩි චීස් කොත්තු", ta: "முட்டை பலண்டி சீஸ் கொத்து" }, category: "palandi_cheese_kotthu", prices: { "Small": "", "Medium": "", "Large": "" } },
  { id: 68, names: { en: "Special Thandoori Fried Rice", si: "ස්පෙෂල් තන්දූරි ෆ්‍රයිඩ් රයිස්", ta: "சிறப்பு தந்தூரி ப்ரைட் ரைஸ்" }, category: "special_thandoori", prices: { "Small": "", "Medium": "" } },
  { id: 69, names: { en: "Chicken Chinese", si: "චිකන් චයිනීස්", ta: "கோழி சைனீஸ்" }, category: "chinese_fried_rice", prices: { "Small": "", "Medium": "", "Large": "" } },
  { id: 70, names: { en: "Beef Chinese", si: "බීෆ් චයිනීස්", ta: "மாட்டிறைச்சி சைனீஸ்" }, category: "chinese_fried_rice", prices: { "Small": "", "Medium": "", "Large": "" } },
  { id: 71, names: { en: "Mixed Chinese", si: "මික්ස්ඩ් චයිනීස්", ta: "கலப்பு சைனீஸ்" }, category: "chinese_fried_rice", prices: { "Small": "", "Medium": "", "Large": "" } },
  { id: 72, names: { en: "Sea Food Chinese", si: "සී ෆුඩ් චයිනීස්", ta: "கடல் உணவு சைனீஸ்" }, category: "chinese_fried_rice", prices: { "Small": "", "Medium": "", "Large": "" } },
  { id: 73, names: { en: "Chicken Sambusa Special", si: "චිකන් සම්බුසා ස්පෙෂල්", ta: "கோழி சம்புசா சிறப்பு" }, category: "sambusa_special", prices: { "Small": "", "Medium": "", "Large": "" } },
  { id: 74, names: { en: "Beef Sambusa Special", si: "බීෆ් සම්බුසා ස්පෙෂල්", ta: "மாட்டிறைச்சி சம்புசா சிறப்பு" }, category: "sambusa_special", prices: { "Small": "", "Medium": "", "Large": "" } },
  { id: 75, names: { en: "Mixed Sambusa Special", si: "මික්ස්ඩ් සම්බුසා ස්පෙෂල්", ta: "கலப்பு சம்புசா சிறப்பு" }, category: "sambusa_special", prices: { "Small": "", "Medium": "", "Large": "" } },
  { id: 76, names: { en: "Sea Food Sambusa Special", si: "සී ෆුඩ් සම්බුසා ස්පෙෂල්", ta: "கடல் உணவு சம்புசா சிறப்பு" }, category: "sambusa_special", prices: { "Small": "", "Medium": "", "Large": "" } },
  { id: 77, names: { en: "Chicken Mongolian", si: "චිකන් මොන්ගෝලියන්", ta: "கோழி மங்கோலியன்" }, category: "mongolian_fried_rice", prices: { "Small": "", "Medium": "", "Large": "" } },
  { id: 78, names: { en: "Beef Mongolian", si: "බීෆ් මොන්ගෝලියන්", ta: "மாட்டிறைச்சி மங்கோலியன்" }, category: "mongolian_fried_rice", prices: { "Small": "", "Medium": "", "Large": "" } },
  { id: 79, names: { en: "Mixed Mongolian", si: "මික්ස්ඩ් මොන්ගෝලියන්", ta: "கலப்பு மங்கோலியன்" }, category: "mongolian_fried_rice", prices: { "Small": "", "Medium": "", "Large": "" } },
  { id: 80, names: { en: "Sea Food Mongolian", si: "සී ෆුඩ් මොන්ගෝලියන්", ta: "கடல் உணவு மங்கோலியன்" }, category: "mongolian_fried_rice", prices: { "Small": "", "Medium": "", "Large": "" } },
  { id: 81, names: { en: "Butter Naan", si: "බටර් නාන්", ta: "வெண்ணெய் நான்" }, category: "naan", price: "" },
  { id: 82, names: { en: "Garlic Naan", si: "ගාර්ලික් නාන්", ta: "பூண்டு நான்" }, category: "naan", price: "" },
  { id: 83, names: { en: "Cheese Naan", si: "චීස් නාන්", ta: "சீஸ் நான்" }, category: "naan", price: "" },
  { id: 84, names: { en: "Butter Chicken Masala", si: "බටර් චිකන් මසාලා", ta: "வெண்ணெய் கோழி மசாலா" }, category: "indian_masala", price: "" },
  { id: 85, names: { en: "Butter Beef Masala", si: "බටර් බීෆ් මසාලා", ta: "வெண்ணெய் மாட்டிறைச்சி மசாலா" }, category: "indian_masala", price: "" },
  { id: 86, names: { en: "Thandoori Chicken Masala", si: "තන්දූරි චිකන් මසාලා", ta: "தந்தூரி கோழி மசாலா" }, category: "indian_masala", price: "" },
  { id: 87, names: { en: "Prawns Masala", si: "ඉස්සෝ මසාලා", ta: "இறால் மசாலா" }, category: "indian_masala", price: "" },
  { id: 88, names: { en: "Cuttle Fish Masala", si: "දැල්ලෝ මසාලා", ta: "கணவாய் மீன் மசாலா" }, category: "indian_masala", price: "" },
  { id: 89, names: { en: "Orange Juice", si: "දොඩම් යුෂ", ta: "ஆரஞ்சு பழச்சாறு" }, category: "fresh_juice", price: "" },
  { id: 90, names: { en: "Mango Juice", si: "අඹ යුෂ", ta: "மாம்பழச் சாறு" }, category: "fresh_juice", price: "" },
  { id: 91, names: { en: "Papaya Juice", si: "ගස්ලබු යුෂ", ta: "பப்பாளி சாறு" }, category: "fresh_juice", price: "" },
  { id: 92, names: { en: "Mixed Juice", si: "මික්ස්ඩ් ජූස්", ta: "கலப்பு பழச்சாறு" }, category: "fresh_juice", price: "" },
  { id: 93, names: { en: "Lime Juice", si: "දෙහි යුෂ", ta: "எலுமிச்சை சாறு" }, category: "fresh_juice", price: "" },
  { id: 94, names: { en: "Falooda Juice", si: "ෆලූඩා", ta: "பலுடா" }, category: "fresh_juice", price: "" },
  { id: 95, names: { en: "Milk Shake", si: "මිල්ක් ශේක්", ta: "மில்க் ஷேக்" }, category: "fresh_juice", price: "" },
  { id: 96, names: { en: "Milk Appam", si: "කිරි ආප්ප", ta: "பால் அப்பம்" }, category: "appam", price: "" },
  { id: 97, names: { en: "Cheese Appam", si: "චීස් ආප්ප", ta: "சீஸ் அப்பம்" }, category: "appam", price: "" },
  { id: 98, names: { en: "Chocolate Appam", si: "චොකලට් ආප්ප", ta: "சாக்லேட் அப்பம்" }, category: "appam", price: "" },
  { id: 99, names: { en: "Milk Mite Appam", si: "මිල්ක්මේඩ් ආප්ප", ta: "மில்க்மெய்ட் அப்பம்" }, category: "appam", price: "" },
  { id: 100, names: { en: "Masala Appam (Beef/Chicken/Prawns)", si: "මසාලා ආප්ප (බීෆ්/චිකන්/ඉස්සෝ)", ta: "மசாலா அப்பம் (மாட்டிறைச்சி/கோழி/இறால்)" }, category: "appam", price: "" },
  { id: 101, names: { en: "Egg Appam", si: "බිත්තර ආප්ප", ta: "முட்டை அப்பம்" }, category: "appam", price: "" },
  { id: 102, names: { en: "Beef Dum Briyani", si: "බීෆ් දම් බිරියානි", ta: "மாட்டிறைச்சி தம் பிரியாணி" }, category: "dum_briyani", prices: { "Small": 900, "Medium": 1100 } },
  { id: 103, names: { en: "Chicken Dum Briyani", si: "චිකන් දම් බිරියානි", ta: "கோழி தம் பிரியாணி" }, category: "dum_briyani", prices: { "Small": 800, "Medium": 1050 } },
  { id: 104, names: { en: "Vegetable Dum Briyani", si: "එළවළු දම් බිරියානි", ta: "மரக்கறி தம் பிரியாணி" }, category: "dum_briyani", prices: { "Small": "", "Medium": "" } },
  { id: 105, names: { en: "Beef Fried Rice", si: "බීෆ් ෆ්‍රයිඩ් රයිස්", ta: "மாட்டிறைச்சி ப்ரைட் ரைஸ்" }, category: "fried_rice", prices: { "Small": 800, "Medium": 1000 } },
  { id: 106, names: { en: "Chicken Fried Rice", si: "චිකන් ෆ්‍රයිඩ් රයිස්", ta: "கோழி ப்ரைட் ரைஸ்" }, category: "fried_rice", prices: { "Small": 700, "Medium": 900 } },
  { id: 107, names: { en: "Egg Fried Rice", si: "බිත්තර ෆ්‍රයිඩ් රයිස්", ta: "முட்டை ப்ரைட் ரைஸ்" }, category: "fried_rice", prices: { "Small": 400, "Medium": 650 } },
  { id: 108, names: { en: "Mixed Fried Rice", si: "මික්ස්ඩ් ෆ්‍රයිඩ් රයිස්", ta: "கலப்பு ப்ரைட் ரைஸ்" }, category: "fried_rice", prices: { "Small": 900, "Medium": 1300 } },
  { id: 109, names: { en: "Fish Fried Rice", si: "මාළු ෆ්‍රයිඩ් රයිස්", ta: "மீன் ப்ரைட் ரைஸ்" }, category: "fried_rice", prices: { "Small": 650, "Medium": 850 } },
  { id: 110, names: { en: "Prawn Fried Rice", si: "ඉස්සෝ ෆ්‍රයිඩ් රයිස්", ta: "இறால் ப்ரைட் ரைஸ்" }, category: "fried_rice", prices: { "Small": 700, "Medium": 900 } },
  { id: 111, names: { en: "Sea Food Fried Rice", si: "සී ෆුඩ් ෆ්‍රයිඩ් රයිස්", ta: "கடல் உணவு ப்ரைட் ரைஸ்" }, category: "fried_rice", prices: { "Small": 1000, "Medium": 1500 } },
  { id: 112, names: { en: "Chicken Dolphin", si: "චිකන් ඩොල්ෆින්", ta: "கோழி டால்பின்" }, category: "dolphin", prices: { "Small": "", "Medium": "", "Large": "" } },
  { id: 113, names: { en: "Beef Dolphin", si: "බීෆ් ඩොල්ෆින්", ta: "மாட்டிறைச்சி டால்பின்" }, category: "dolphin", prices: { "Small": "", "Medium": "", "Large": "" } },
  { id: 114, names: { en: "Mixed Dolphin", si: "මික්ස්ඩ් ඩොල්ෆින්", ta: "கலப்பு டால்பின்" }, category: "dolphin", prices: { "Small": "", "Medium": "", "Large": "" } },
  { id: 115, names: { en: "Vegetable Dolphin", si: "එළවළු ඩොල්ෆින්", ta: "மரக்கறி டால்பின்" }, category: "dolphin", prices: { "Small": "", "Medium": "", "Large": "" } },
  { id: 116, names: { en: "Chicken Noodles", si: "චිකන් නූඩ්ලස්", ta: "கோழி நூடுல்ஸ்" }, category: "noodles", prices: { "Small": "", "Medium": "", "Large": "" } },
  { id: 117, names: { en: "Beef Noodles", si: "බීෆ් නූඩ්ලස්", ta: "மாட்டிறைச்சி நூடுல்ஸ்" }, category: "noodles", prices: { "Small": "", "Medium": "", "Large": "" } },
  { id: 118, names: { en: "Mixed Noodles", si: "මික්ස්ඩ් නූඩ්ලස්", ta: "கலப்பு நூடுல்ஸ்" }, category: "noodles", prices: { "Small": "", "Medium": "", "Large": "" } },
  { id: 119, names: { en: "Vegetable Noodles", si: "එළවළු නූඩ්ලස්", ta: "மரக்கறி நூடுல்ஸ்" }, category: "noodles", prices: { "Small": "", "Medium": "", "Large": "" } },
  { id: 120, names: { en: "Egg Noodles", si: "බිත්තර නූඩ්ලස්", ta: "முட்டை நூடுல்ஸ்" }, category: "noodles", prices: { "Small": "", "Medium": "", "Large": "" } },
  { id: 121, names: { en: "Chicken Macaroni", si: "චිකන් මැකරෝනි", ta: "கோழி மாக்கரோனி" }, category: "macaroni", prices: { "Small": "", "Medium": "", "Large": "" } },
  { id: 122, names: { en: "Beef Macaroni", si: "බීෆ් මැකරෝනි", ta: "மாட்டிறைச்சி மாக்கரோனி" }, category: "macaroni", prices: { "Small": "", "Medium": "", "Large": "" } },
  { id: 123, names: { en: "Mixed Macaroni", si: "මික්ස්ඩ් මැකරෝනි", ta: "கலப்பு மாக்கரோனி" }, category: "macaroni", prices: { "Small": "", "Medium": "", "Large": "" } },
  { id: 124, names: { en: "Vegetable Macaroni", si: "එළවළු මැකරෝනි", ta: "மரக்கறி மாக்கரோனி" }, category: "macaroni", prices: { "Small": "", "Medium": "", "Large": "" } },
  { id: 125, names: { en: "Egg Macaroni", si: "බිත්තර මැකරෝනි", ta: "முட்டை மாக்கரோனி" }, category: "macaroni", prices: { "Small": "", "Medium": "", "Large": "" } },
  { id: 126, names: { en: "Maravalli with Roast (Babath/Liver)", si: "මඤ්ඤොක්කා රෝස්ට් සමඟ", ta: "மரவள்ளி ரோஸ்டுடன்" }, category: "maravalli_special", prices: { "Small": "", "Medium": "", "Large": "" } },
  { id: 127, names: { en: "Maravalli with Babath & Curry", si: "මඤ්ඤොක්කා කරි සමඟ", ta: "மரவள்ளி கறியுடன்" }, category: "maravalli_special", prices: { "Small": "", "Medium": "", "Large": "" } },
  { id: 128, names: { en: "Chicken Soup (Any Time)", si: "චිකන් සුප්", ta: "கோழி சூப்" }, category: "soup", price: "" },
  { id: 129, names: { en: "Beef Soup (Sunday Only)", si: "බීෆ් සුප්", ta: "மாட்டிறைச்சி சூப்" }, category: "soup", price: "" },
  { id: 130, names: { en: "Mutton Soup (Saturday Only)", si: "මට්න් සුප්", ta: "ஆட்டிறைச்சி சூப்" }, category: "soup", price: "" },
  { id: 131, names: { en: "Veg Soup (Any Time)", si: "එළවළු සුප්", ta: "மரக்கறி சூப்" }, category: "soup", price: "" },
  { id: 132, names: { en: "Egg Soup (Any Time)", si: "බිත්තර සුප්", ta: "முட்டை சூப்" }, category: "soup", price: "" },
  { id: 133, names: { en: "Baratta Package", si: "පරාටා පැකේජය", ta: "பரோட்டா பொதி" }, category: "breakfast_packages", prices: { "Option 1": 150, "Option 2": 200, "Option 3": 250, "Option 4": 300 } },
  { id: 134, names: { en: "Idiyappa Package", si: "ඉඳිආප්ප පැකේජය", ta: "இடியாப்ப பொதி" }, category: "breakfast_packages", prices: { "Option 1": "", "Option 2": 200, "Option 3": 250, "Option 4": 300 } },
  { id: 135, names: { en: "Pittu Package", si: "පිට්ටු පැකේජය", ta: "பிட்டு பொதி" }, category: "breakfast_packages", prices: { "Option 1": "", "Option 2": "", "Option 3": "", "Option 4": "" } },
  { id: 136, names: { en: "Vattilappam", si: "වටලප්පන්", ta: "வட்டிலப்பம்" }, category: "desserts", price: "" }
];

export const categories = [
  // KOTTU
  { id: "koththu", label: "Koththu (Rotti Or String Hoppers)", page: "Kottu" },
  { id: "palandi_kottu", label: "Palandi Kottu", page: "Kottu" },
  { id: "palandi_cheese_kotthu", label: "Palandi Cheese Kotthu", page: "Kottu" },

  // RICE
  { id: "fried_rice", label: "Fried Rice (Samba or Ponni Rice)", page: "Rice" },
  { id: "grill_chicken", label: "Grill Chicken Fried Rice", page: "Rice" },
  { id: "chinese_fried_rice", label: "Chinese Fried Rice (Basmati)", page: "Rice" },
  { id: "special_thandoori", label: "Special Thandoori Fried Rice", page: "Rice" },
  { id: "nasi_goreng", label: "Malay Nasi Goreng", page: "Rice" },
  { id: "mongolian_fried_rice", label: "Mongolian Fried Rice", page: "Rice" },
  { id: "biryani", label: "Biryani Samba Or Ponni Rice", page: "Rice" },
  { id: "bamboo_briyani", label: "Bamboo Briyani", page: "Rice" },
  { id: "dum_briyani", label: "Dum Briyani (Samba or Ponni Rice)", page: "Rice" },
  { id: "sambusa_special", label: "Sambusa Special Cheese & Nuts Omelette Rice", page: "Rice" },

  // BREAKFAST & LUNCH
  { id: "breakfast", label: "Breakfast", page: "Breakfast & Lunch" },
  { id: "lunch", label: "Lunch", page: "Breakfast & Lunch" },
  { id: "breakfast_packages", label: "Break Fast Packages", page: "Breakfast & Lunch" },
  { id: "appam", label: "Appam", page: "Breakfast & Lunch" },

  // NOODLES
  { id: "noodles", label: "Noodles", page: "Noodles" },
  { id: "macaroni", label: "Macaroni", page: "Noodles" },

  // FAST FOOD
  { id: "soup", label: "Soup", page: "Fast Food" },
  { id: "naan", label: "Naan With Chana Masala", page: "Fast Food" },
  { id: "indian_masala", label: "Indian Masala", page: "Fast Food" },
  { id: "dolphin", label: "Dolphin (Naan Rotti or Baratta Rotti)", page: "Fast Food" },
  { id: "maravalli_special", label: "KKY Maravalli Special", page: "Fast Food" },
  { id: "desserts", label: "Desserts", page: "Fast Food" },

  // DRINKS
  { id: "hot_drinks", label: "Hot Drinks", page: "Drinks" },
  { id: "fresh_juice", label: "Fresh Juice", page: "Drinks" }
];
