export const menuData = [
  { id: 1, names: { en: "Baratta", si: "පරාටා", ta: "பரோட்டா" }, category: "breakfast", price: 50 },
  { id: 2, names: { en: "Idiyappam", si: "ඉඳිආප්ප", ta: "இடியப்பம்" }, category: "breakfast", price: 90 },
  { id: 3, names: { en: "Pittu", si: "පිට්ටු", ta: "பிட்டு" }, category: "breakfast", price: 120 },
  { id: 4, names: { en: "Pittu (Mani)", si: "මනි පිට්ටු", ta: "மணி பிட்டு" }, category: "breakfast", price: 100 },
  { id: 5, names: { en: "Paruppu vadai", si: "පරිප්පු වඩේ", ta: "பருப்பு வடை" }, category: "breakfast", price: 30 },
  { id: 6, names: { en: "Thattu Rotti", si: "තට්ටු රොටි", ta: "தட்டு ரொட்டி" }, category: "breakfast", price: 50 },
  { id: 7, names: { en: "Ulundu vadai", si: "උළුඳු වඩේ", ta: "உளுந்து வடை" }, category: "breakfast", price: 80 },
  { id: 8, names: { en: "Koli Appam", si: "කොලි ආප්ප", ta: "கோழி அப்பம்" }, category: "breakfast", price: 60 },
  { id: 9, names: { en: "Iraehchi Rotti", si: "මස් රොටි", ta: "இறைச்சி ரொட்டி" }, category: "breakfast", price: 130 },
  { id: 10, names: { en: "Chicken Rotti", si: "චිකන් රොටි", ta: "கோழி ரொட்டி" }, category: "breakfast", price: 130 },
  { id: 11, names: { en: "Veg Rotti", si: "එළවළු රොටි", ta: "மரக்கறி ரொட்டி" }, category: "breakfast", price: 100 },
  { id: 12, names: { en: "Beef Bun", si: "බීෆ් බන්", ta: "மாட்டிறைச்சி பன்" }, category: "breakfast", price: 150 },
  { id: 13, names: { en: "Chicken Bun", si: "චිකන් බන්", ta: "கோழி பன்" }, category: "breakfast", price: 100 },
  { id: 14, names: { en: "Egg Roll", si: "බිත්තර රෝල්", ta: "முட்டை ரோல்" }, category: "breakfast", price: 130 },
  { id: 15, names: { en: "Samosa Beef/Chicken", si: "සමෝසා බීෆ්/චිකන්", ta: "சமோசா மாட்டிறைச்சி/கோழி" }, category: "breakfast", price: 80 },
  { id: 16, names: { en: "Veg Roll", si: "එළවළු රෝල්", ta: "மரக்கறி ரோல்" }, category: "breakfast", price: 60 },
  { id: 17, names: { en: "Pettes", si: "පැටිස්", ta: "பாட்டிஸ்" }, category: "breakfast", price: 70 },
  { id: 18, names: { en: "Egg Rotti", si: "බිත්තර රොටි", ta: "முட்டை ரொட்டி" }, category: "breakfast", price: 130 },
  { id: 19, names: { en: "Dosa", si: "තෝසේ", ta: "தோசை" }, category: "breakfast", price: 80 },
  { id: 20, names: { en: "Red Rice", si: "රතු බත්", ta: "சிவப்பு அரிசி" }, category: "breakfast", price: 300 },
  { id: 21, names: { en: "Noodles", si: "නූඩ්ලස්", ta: "நூடுல்ஸ்" }, category: "breakfast", price: 330 },
  { id: 22, names: { en: "Chee Rotti", si: "චී රොටි", ta: "சீ ரொட்டி" }, category: "breakfast", price: 180 },
  { id: 23, names: { en: "Cheese Rotti", si: "චීස් රොටි", ta: "சீஸ் ரொட்டி" }, category: "breakfast", price: 150 },
  { id: 24, names: { en: "Lunch Rotti (Veechi Rotti)", si: "වීසි රොටි", ta: "வீச்சு ரொட்டி" }, category: "breakfast", price: 50 },
  { id: 25, names: { en: "Omlet Bun", si: "ඔම්ලට් බන්", ta: "ஆம்லெட் பன்" }, category: "breakfast", price: 120 },
  { id: 26, names: { en: "Rice & Curry (Fish)", si: "බත් සහ මාළු කරි", ta: "சோறு மற்றும் மீன் கறி" }, category: "lunch", price: 500 },
  { id: 27, names: { en: "Rice & Curry (Beef)", si: "බත් සහ බීෆ් කරි", ta: "சோறு மற்றும் மாட்டிறைச்சி கறி" }, category: "lunch", price: 600 },
  { id: 28, names: { en: "Rice & Curry (Chicken)", si: "බත් සහ චිකන් කරි", ta: "சோறு மற்றும் கோழி கறி" }, category: "lunch", price: 550 },
  { id: 29, names: { en: "Rice & Curry (Egg)", si: "බත් සහ බිත්තර කරි", ta: "சோறு மற்றும் முட்டை கறி" }, category: "lunch", price: 400 },
  { id: 30, names: { en: "Rice & Curry (Vegetable)", si: "බත් සහ එළවළු කරි", ta: "சோறு மற்றும் மரக்கறி கறி" }, category: "lunch", price: 300 },
  { id: 31, names: { en: "Beef Malay Nasi Goreng", si: "බීෆ් මැලේ නාසි ගුරාන්", ta: "மாட்டிறைச்சி மலாய் நாசி கோரெங்" }, category: "nasi_goreng", prices: { "Small": 1000, "Medium": 1500, "Large": 3000 } },
  { id: 32, names: { en: "Chicken Malay Nasi Goreng", si: "චිකන් මැලේ නාසි ගුරාන්", ta: "கோழி மலாய் நாசி கோரெங்" }, category: "nasi_goreng", prices: { "Small": 1000, "Medium": 1400, "Large": 2800 } },
  { id: 33, names: { en: "Mixed Malay Nasi Goreng", si: "මික්ස්ඩ් මැලේ නාසි ගුරාන්", ta: "கலப்பு மலாய் நாசி கோரெங்" }, category: "nasi_goreng", prices: { "Small": 1250, "Medium": 1700, "Large": 3500 } },
  { id: 34, names: { en: "Sea Food Malay Nasi Goreng", si: "සී ෆුඩ් මැලේ නාසි ගුරාන්", ta: "கடல் உணவு மலாய் நாசி கோரெங்" }, category: "nasi_goreng", prices: { "Small": 1250, "Medium": 1700, "Large": 3500 } },
  { id: 35, names: { en: "Special Grill Chicken Fried Rice", si: "ස්පෙෂල් ග්‍රිල් චිකන් ෆ්‍රයිඩ් රයිස්", ta: "சிறப்பு கிரில் சிக்கன் ப்ரைட் ரைஸ்" }, category: "grill_chicken", prices: { "Small": 1000, "Medium": 1500, "Large": 3500 } },
  { id: 36, names: { en: "Egg Biriyani", si: "බිත්තර බිරියානි", ta: "முட்டை பிரியாணி" }, category: "biryani", prices: { "Small": 400, "Medium": 650, "Large": 1500 } },
  { id: 37, names: { en: "Vegetable Briyani", si: "එළවළු බිරියානි", ta: "மரக்கறி பிரியாணி" }, category: "biryani", prices: { "Small": 350, "Medium": 550 } },
  { id: 38, names: { en: "Fish Briyani", si: "මාළු බිරියානි", ta: "மீன் பிரியாணி" }, category: "biryani", prices: { "Small": 650, "Medium": 850 } },
  { id: 39, names: { en: "Beef Briyan", si: "බීෆ් බිරියානි", ta: "மாட்டிறைச்சி பிரியாணி" }, category: "biryani", prices: { "Small": 750, "Medium": 950, "Large": 2000 } },
  { id: 40, names: { en: "Chicken Briyani", si: "චිකන් බිරියානි", ta: "கோழி பிரியாணி" }, category: "biryani", prices: { "Small": 700, "Medium": 900, "Large": 2000 } },
  { id: 41, names: { en: "Chicken Koththu", si: "චිකන් කොත්තු", ta: "கோழி கொத்து" }, category: "koththu", prices: { "Small": 700, "Medium": 900 } },
  { id: 42, names: { en: "Prawns Koththu", si: "ඉස්සෝ කොත්තු", ta: "இறால் கொத்து" }, category: "koththu", prices: { "Small": 700, "Medium": 900 } },
  { id: 43, names: { en: "Beef Koththu", si: "බීෆ් කොත්තු", ta: "மாட்டிறைச்சி கொத்து" }, category: "koththu", prices: { "Small": 750, "Medium": 950 } },
  { id: 44, names: { en: "Sea Food Koththu", si: "සී ෆුඩ් කොත්තු", ta: "கடல் உணவு கொத்து" }, category: "koththu", prices: { "Small": 900, "Medium": 1400 } },
  { id: 45, names: { en: "Mixed Koththu", si: "මික්ස්ඩ් කොත්තු", ta: "கலப்பு கொத்து" }, category: "koththu", prices: { "Small": 1100, "Medium": 1500 } },
  { id: 46, names: { en: "Devilled Beef", si: "ඩෙවිල්ඩ් බීෆ්", ta: "டெவில்ட் மாட்டிறைச்சி" }, category: "koththu", prices: { "Small": 900, "Medium": 1300 } },
  { id: 47, names: { en: "Chicken Cheese Koththu", si: "චිකන් චීස් කොත්තු", ta: "கோழி சீஸ் கொத்து" }, category: "koththu", prices: { "Small": 1000, "Medium": 1400 } },
  { id: 48, names: { en: "Beef Cheese Koththu", si: "බීෆ් චීස් කොත්තු", ta: "மாட்டிறைச்சி சீஸ் கொத்து" }, category: "koththu", prices: { "Small": 1100, "Medium": 1500 } },
  { id: 49, names: { en: "Mixed Cheese Koththu", si: "මික්ස්ඩ් චීස් කොත්තු", ta: "கலப்பு சீஸ் கொத்து" }, category: "koththu", prices: { "Small": 1300, "Medium": 1600 } },
  { id: 50, names: { en: "Milk Tea", si: "කිරි තේ", ta: "பால் தேநீர்" }, category: "hot_drinks", price: 160 },
  { id: 51, names: { en: "Milk Powder Tea", si: "කිරිපිටි තේ", ta: "பால் பவுடர் தேநீர்" }, category: "hot_drinks", price: 120 },
  { id: 52, names: { en: "Plain Tea", si: "ප්ලේන් ටී", ta: "வெறும் தேநீர்" }, category: "hot_drinks", price: 50 },
  { id: 53, names: { en: "Plain Tea Special", si: "ස්පෙෂල් ප්ලේන් ටී", ta: "சிறப்பு வெறும் தேநீர்" }, category: "hot_drinks", price: 80 },
  { id: 54, names: { en: "Coffee", si: "කෝපි", ta: "காபி" }, category: "hot_drinks", price: 80 },
  { id: 55, names: { en: "Nest Coffee", si: "නෙස් කෝපි", ta: "நெஸ் காபி" }, category: "hot_drinks", price: 140 },
  { id: 56, names: { en: "Nestomalt", si: "නෙස්ටෝමෝල්ට්", ta: "நெஸ்டோமால்ட்" }, category: "hot_drinks", price: 120 },
  { id: 57, names: { en: "Milk Coffee", si: "කිරි කෝපි", ta: "பால் காபி" }, category: "hot_drinks", price: 150 },
  { id: 58, names: { en: "Kava Tea", si: "කාවා තේ", ta: "காவா தேநீர்" }, category: "hot_drinks", price: 160 },
  { id: 59, names: { en: "Take Away Cup Charges", si: "ටේක් අවේ කෝප්ප ගාස්තු", ta: "பார்சல் கப் கட்டணம்" }, category: "hot_drinks", price: 20 },
  { id: 60, names: { en: "Chicken Palandi Kottu", si: "චිකන් පලන්ඩි කොත්තු", ta: "கோழி பலண்டி கொத்து" }, category: "palandi_kottu", prices: { "Small": "", "Medium": "", "Large": "" } },
  { id: 61, names: { en: "Beef Palandi Kottu", si: "බීෆ් පලන්ඩි කොත්තු", ta: "மாட்டிறைச்சி பலண்டி கொத்து" }, category: "palandi_kottu", prices: { "Small": "", "Medium": "", "Large": "" } },
  { id: 62, names: { en: "Egg Palandi Kottu", si: "බිත්තර පලන්ඩි කොත්තු", ta: "முட்டை பலண்டி கொத்து" }, category: "palandi_kottu", prices: { "Small": "", "Medium": "", "Large": "" } },
  { id: 63, names: { en: "Chicken Bamboo Briyani", si: "චිකන් බම්බු බිරියානි", ta: "கோழி மூங்கில் பிரியாணி" }, category: "bamboo_briyani", prices: { "Small": "", "Medium": "", "Large": "" } },
  { id: 64, names: { en: "Beef Bamboo Briyani", si: "බීෆ් බම්බු බිරියානි", ta: "மாட்டிறைச்சி மூங்கில் பிரியாணி" }, category: "bamboo_briyani", prices: { "Small": "", "Medium": "", "Large": "" } },
  { id: 65, names: { en: "Chicken Palandi Cheese Kottu", si: "චිකන් පලන්ඩි චීස් කොත්තු", ta: "கோழி பலண்டி சீஸ் கொத்து" }, category: "palandi_cheese_kotthu", prices: { "Small": "", "Medium": "", "Large": "" } },
  { id: 66, names: { en: "Beef Palandi Cheese Kottu", si: "බීෆ් පලන්ඩි චීස් කොත්තු", ta: "மாட்டிறைச்சி பலண்டி சீஸ் கொத்து" }, category: "palandi_cheese_kotthu", prices: { "Small": "", "Medium": "", "Large": "" } },
  { id: 67, names: { en: "Egg Palandi Cheese Kottu", si: "බිත්තර පලන්ඩි චීස් කොත්තු", ta: "முட்டை பலண்டி சீஸ் கொத்து" }, category: "palandi_cheese_kotthu", prices: { "Small": "", "Medium": "", "Large": "" } },
  { id: 68, names: { en: "Special Thandoori Fried Rice", si: "ස්පෙෂල් තන්දූරි ෆ්‍රයිඩ් රයිස්", ta: "சிறப்பு தந்தூரி ப்ரைட் ரைஸ்" }, category: "special_thandoori", prices: { "Small": "", "Medium": "" } },
  { id: 69, names: { en: "Chicken Chinese", si: "චිකන් චයිනීස්", ta: "கோழி சைனீஸ்" }, category: "chinese_fried_rice", prices: { "Small": "", "Medium": "", "Large": "" } },
  { id: 70, names: { en: "Beef Chinese", si: "බීෆ් චයිනීස්", ta: "மாட்டிறைச்சி சைனீஸ்" }, category: "chinese_fried_rice", prices: { "Small": "", "Medium": "", "Large": "" } },
  { id: 71, names: { en: "Mixed Chinese", si: "මික්ස්ඩ් චයිනීස්", ta: "கலப்பு சைனீஸ்" }, category: "chinese_fried_rice", prices: { "Small": "", "Medium": "", "Large": "" } },
  { id: 72, names: { en: "Sea Food Chinese", si: "සී ෆුඩ් චයිනීස්", ta: "கடல் உணவு சைனீஸ்" }, category: "chinese_fried_rice", prices: { "Small": "", "Medium": "", "Large": "" } }
];

export const categories = [
  { id: "breakfast", label: "Breakfast" },
  { id: "lunch", label: "Lunch" },
  { id: "nasi_goreng", label: "Malay Nasi Goreng" },
  { id: "grill_chicken", label: "Grill Chicken Fried Rice" },
  { id: "biryani", label: "Biryani Samba Or Ponni Rice" },
  { id: "koththu", label: "Koththu (Rotti Or String Hoppers)" },
  { id: "hot_drinks", label: "Hot Drinks" },
  { id: "palandi_kottu", label: "Palandi Kottu" },
  { id: "bamboo_briyani", label: "Bamboo Briyani" },
  { id: "palandi_cheese_kotthu", label: "Palandi Cheese Kotthu" },
  { id: "special_thandoori", label: "Special Thandoori Fried Rice" },
  { id: "chinese_fried_rice", label: "Chinese Fried Rice (Basmati)" }
];
