export const menuData = [
  { id: 1, names: { en: "Baratta", si: "පරාටා", ta: "பரோட்டா" }, category: "breakfast", price: 50 },
  { id: 2, names: { en: "Idiyappam", si: "ඉඳිආප්ප", ta: "இடியப்பம்" }, category: "breakfast", price: 90 },
  { id: 3, names: { en: "Pittu", si: "පිට්ටු", ta: "பிட்டு" }, category: "breakfast", price: 120 },
  { id: 4, names: { en: "Pittu (Mani)", si: "මනි පිට්ටු", ta: "மணி பிட்டு" }, category: "breakfast", price: 100 },
  { id: 5, names: { en: "Paruppu vadai", si: "පරිප්පු වඩේ", ta: "பருப்பு வடை" }, category: "breakfast", price: 30 },
  { id: 6, names: { en: "Thattu Rotti", si: "තට්ටු රොටි", ta: "தட்டு ரொட்டி" }, category: "breakfast", price: 50 },
  { id: 7, names: { en: "Ulundu vadai", si: "උළුඳු වඩේ", ta: "உளுந்து வடை" }, category: "breakfast", price: 80 },
  { id: 8, names: { en: "Koli Appam", si: "කොලි ආප්ප", ta: "கோழி அப்பம்" }, category: "breakfast", price: 60 },
  { id: 9, names: { en: "Iraehchi Rotti", si: "මස් රොටි", ta: "இறைச்சி ரொட்டி" }, category: "breakfast", price: 130 },
  { id: 10, names: { en: "Chicken Rotti", si: "චිකන් රොටි", ta: "கோழி ரொட்டி" }, category: "breakfast", price: 130 },
  { id: 11, names: { en: "Veg Rotti", si: "එළවළු රොටි", ta: "மரக்கறி ரொட்டி" }, category: "breakfast", price: 100 },
  { id: 12, names: { en: "Beef Bun", si: "බීෆ් බන්", ta: "மாட்டிறைச்சி பன்" }, category: "breakfast", price: 150 },
  { id: 13, names: { en: "Chicken Bun", si: "චිකන් බන්", ta: "கோழி பன்" }, category: "breakfast", price: 100 },
  { id: 14, names: { en: "Egg Roll", si: "බිත්තර රෝල්", ta: "முட்டை ரோல்" }, category: "breakfast", price: 130 },
  { id: 15, names: { en: "Samosa Beef/Chicken", si: "සමෝසා බීෆ්/චිකන්", ta: "சமோசா மாட்டிறைச்சி/கோழி" }, category: "breakfast", price: 80 },
  { id: 16, names: { en: "Veg Roll", si: "එළවළු රෝල්", ta: "மரக்கறி ரோல்" }, category: "breakfast", price: 60 },
  { id: 17, names: { en: "Pettes", si: "පැටිස්", ta: "பாட்டிஸ்" }, category: "breakfast", price: 70 },
  { id: 18, names: { en: "Egg Rotti", si: "බිත්තර රොටි", ta: "முட்டை ரொட்டி" }, category: "breakfast", price: 130 },
  { id: 19, names: { en: "Dosa", si: "තෝසේ", ta: "தோசை" }, category: "breakfast", price: 80 },
  { id: 20, names: { en: "Red Rice", si: "රතු බත්", ta: "சிவப்பு அரிசி" }, category: "breakfast", price: 300 },
  { id: 21, names: { en: "Noodles", si: "නූඩ්ලස්", ta: "நூடுல்ஸ்" }, category: "breakfast", price: 330 },
  { id: 22, names: { en: "Chee Rotti", si: "චී රොටි", ta: "சீ ரொட்டி" }, category: "breakfast", price: 180 },
  { id: 23, names: { en: "Cheese Rotti", si: "චීස් රොටි", ta: "சீஸ் ரொட்டி" }, category: "breakfast", price: 150 },
  { id: 24, names: { en: "Lunch Rotti (Veechi Rotti)", si: "වීසි රොටි", ta: "வீச்சு ரொட்டி" }, category: "breakfast", price: 50 },
  { id: 25, names: { en: "Omlet Bun", si: "ඔම්ලට් බන්", ta: "ஆம்லெட் பன்" }, category: "breakfast", price: 120 },
  { id: 26, names: { en: "Rice & Curry (Fish)", si: "බත් සහ මාළු කරි", ta: "சோறு மற்றும் மீன் கறி" }, category: "lunch", price: 500 },
  { id: 27, names: { en: "Rice & Curry (Beef)", si: "බත් සහ බීෆ් කරි", ta: "சோறு மற்றும் மாட்டிறைச்சி கறி" }, category: "lunch", price: 600 },
  { id: 28, names: { en: "Rice & Curry (Chicken)", si: "බත් සහ චිකන් කරි", ta: "சோறு மற்றும் கோழி கறி" }, category: "lunch", price: 550 },
  { id: 29, names: { en: "Rice & Curry (Egg)", si: "බත් සහ බිත්තර කරි", ta: "சோறு மற்றும் முட்டை கறி" }, category: "lunch", price: 400 },
  { id: 30, names: { en: "Rice & Curry (Vegetable)", si: "බත් සහ එළවළු කරි", ta: "சோறு மற்றும் மரக்கறி கறி" }, category: "lunch", price: 300 },
  { id: 31, names: { en: "Beef Malay Nasi Goreng", si: "බීෆ් මැලේ නාසි ගුරාන්", ta: "மாட்டிறைச்சி மலாய் நாசி கோரெங்" }, category: "nasi_goreng", prices: { "Small": 1000, "Medium": 1500, "Large": 3000 } },
  { id: 32, names: { en: "Chicken Malay Nasi Goreng", si: "චිකන් මැලේ නාසි ගුරාන්", ta: "கோழி மலாய் நாசி கோரெங்" }, category: "nasi_goreng", prices: { "Small": 1000, "Medium": 1400, "Large": 2800 } },
  { id: 33, names: { en: "Mixed Malay Nasi Goreng", si: "මික්ස්ඩ් මැලේ නාසි ගුරාන්", ta: "கலப்பு மலாய் நாசி கோரெங்" }, category: "nasi_goreng", prices: { "Small": 1250, "Medium": 1700, "Large": 3500 } },
  { id: 34, names: { en: "Sea Food Malay Nasi Goreng", si: "සී ෆුඩ් මැලේ නාසි ගුරාන්", ta: "கடல் உணவு மலாய் நாசி கோரெங்" }, category: "nasi_goreng", prices: { "Small": 1250, "Medium": 1700, "Large": 3500 } },
  { id: 35, names: { en: "Special Grill Chicken Fried Rice", si: "ස්පෙෂල් ග්‍රිල් චිකන් ෆ්‍රයිඩ් රයිස්", ta: "சிறப்பு கிரில் சிக்கன் ப்ரைட் ரைஸ்" }, category: "grill_chicken", prices: { "Small": 1000, "Medium": 1500, "Large": 3500 } }
];

export const categories = [
  { id: "breakfast", label: "Breakfast" },
  { id: "lunch", label: "Lunch" },
  { id: "nasi_goreng", label: "Malay Nasi Goreng" },
  { id: "grill_chicken", label: "Grill Chicken Fried Rice" }
];
